#!/usr/bin/env bash

if [[ "$1" == "--release-build" ]]; then
  cmake_options="-DRELEASE_BUILD=ON"
else
  cmake_options=""
fi

mkdir -p "build"
cd "build"

if [[ "$OS" == "Windows_NT" ]]; then
  cmake -G "MinGW Makefiles" $cmake_options ..
else
  cmake $cmake_options ..
fi

make
./qtlab
